### ISSUE TITLE
(refactored branch) [bug] By config file description of mistakes, Segfault occurs during PostgreSQL start.

### ISSUE THREAD

**Issue by harada-toshi** [ossc-db/pgaudit#46]
# Overview
* By config file description of mistakes, Segfault occurs during PostgreSQL start.
* No message at startup is displayed after "server starting" message.
* Examining the process, the postgres process is not running.
* Postmaster.pid is present in the database cluster.
* A core file exists in the database cluster.

# Config file

```
[output]
        logger = 'serverlog'

# SQL(0)
[rule]
        class = 'READ'

# SQL(1)
        database = 'test'
        class = 'READ'
        object_name = 'public.foo'

# SQL(2)
        database = 'test'
        class = 'WRITE'
        object_name = 'public.foo'

# SQL(3)
        database = 'bad'
        class = 'WRITE'
        object_name = 'public.bar'
```

* I forgot to write [rule]. Does this happen when there are multiple filters in the same rule?

# Execute log.
```
$ pg_ctl -D ~/pgdata/9.6-pgaudit/ start
server starting
$ ps aux | grep post
root      1474  0.0  0.1  93212  2248 ?        Ss   09:53   0:00 /usr/libexec/postfix/master -w
postfix   1494  0.0  0.3  93384  3928 ?        S    09:53   0:00 qmgr -l -t unix -u
postfix  17152  0.0  0.3  93316  3904 ?        S    16:41   0:00 pickup -l -t unix -u
nuko     19725  0.0  0.0 112664   968 pts/0    R+   17:41   0:00 grep --color=auto post
$ ls -l ~/pgdata/9.6-pgaudit/core.19719
-rw-------. 1 nuko nuko 1073152  3月  7 17:41 /home/nuko/pgdata/9.6-pgaudit/core.19719
$ ls -l ~/pgdata/9.6-pgaudit/postmaster.pid
-rw-------. 1 nuko nuko 53  3月  7 17:41 /home/nuko/pgdata/9.6-pgaudit/postmaster.pid
$
```

# Core file (execute gdb log)

```
$ gdb ~/pgsql/pgsql/bin/postgres -c ~/pgdata/9.6-pgaudit/core.19719
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/nuko/pgsql/pgsql-9.6.2/bin/postgres...(no debugging symbols found)...done.
[New LWP 19719]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/home/nuko/pgsql/pgsql-9.6.2/bin/postgres -D /home/nuko/pgdata/9.6-pgaudit'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000007c620a in MemoryContextAlloc ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-105.el7.x86_64 libxml2-2.9.1-6.el7_2.2.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) where
#0  0x00000000007c620a in MemoryContextAlloc ()
#1  0x00000000007c6ca1 in MemoryContextStrdup ()
#2  0x00007f543a238369 in processAuditConfigFile () from /home/nuko/pgsql/pgsql-9.6.2/lib/pgaudit.so
#3  0x00007f543a235ba8 in _PG_init () from /home/nuko/pgsql/pgsql-9.6.2/lib/pgaudit.so
#4  0x00000000007aa7a8 in internal_load_library ()
#5  0x00000000007ab00c in load_file ()
#6  0x00000000007b218b in load_libraries ()
#7  0x00000000007b33ce in process_shared_preload_libraries ()
#8  0x000000000065fc35 in PostmasterMain ()
#9  0x000000000046ced0 in main ()
(gdb)
```

**Comment by MasahikoSawada** [comment]
Thanks.

It's a memory bug. pgaudit could not handle properly when the same field is specified at more than once. Commit b300c17730949d7cc2082ae2ab465d7f49d3c3f6 should fix it.

**Comment by harada-toshi** [comment]
Thank you for bug fixes!

In the bugfix version, I confirmed that it will be the following behavior.
* Segfault did not occur and the PostgreSQL server started up.
* When describing duplicate filter items in one rule, it is overwritten with the description written behind.

# PostgreSQL launch log

```
$ pg_ctl -w -D ~/pgdata/9.6-pgaudit/ start
waiting for server to start....LOG:  detect duplicate field setting "class"in rule section, overwritten by "read"
LOG:  detect duplicate field setting "database"in rule section, overwritten by "test"
LOG:  detect duplicate field setting "class"in rule section, overwritten by "write"
LOG:  detect duplicate field setting "object_name"in rule section, overwritten by "public.foo"
LOG:  detect duplicate field setting "database"in rule section, overwritten by "bad"
LOG:  detect duplicate field setting "class"in rule section, overwritten by "write"
LOG:  detect duplicate field setting "object_name"in rule section, overwritten by "public.bar"
LOG:  log_catalog = 1
LOG:  log_level_string = (null)
LOG:  log_level = 15
LOG:  log_parameter = 0
LOG:  log_statement_once = 0
LOG:  log_for_test = 0
LOG:  role =
LOG:  logger = serverlog
LOG:  facility = (null)
LOG:  priority = (null)
LOG:  ident = (null)
LOG:  option = (null)
LOG:  pathlog = (null)
LOG:  Rule 0
LOG:      STR database = bad
LOG:      BMP class = 256
LOG:      STR object_name = public.bar
LOG:  pgaudit extension initialized
LOG:  database system was shut down at 2017-03-09 15:36:17 JST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  connection received: host=[local]
LOG:  connection authorized: user=nuko database=postgres
```

**Comment by harada-toshi** [comment]
I confirmed the fix. 
Close this Issue.
